//
// Created by msegura on 01/06/19.
//

#ifndef THEINDESTRUCTIBLELIBRARY_DBCONTROLLER_H
#define THEINDESTRUCTIBLELIBRARY_DBCONTROLLER_H


class DBController {

};


#endif //THEINDESTRUCTIBLELIBRARY_DBCONTROLLER_H
