//
// Created by alvar on 01/06/19.
//

#ifndef THEINDESTRUCTIBLELIBRARY_FILEMANAGER_H
#define THEINDESTRUCTIBLELIBRARY_FILEMANAGER_H


class FileManager {

};


#endif //THEINDESTRUCTIBLELIBRARY_FILEMANAGER_H
